name: Docker Image Sync

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  ALIYUN_REGISTRY_USER: "${{ secrets.USERNAME }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.PASSWORD }}"
  env_var: ${{ vars.Docker }}
jobs:

  build:
    runs-on: ubuntu-latest
    environment: docker
    steps:
    - name: Before freeing up disk space
      run: |
        echo "Before freeing up disk space"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    # 增加可用磁盘空间
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:

        root-reserve-mb: 2048
        swap-size-mb: 128
        remove-dotnet: 'true'
        remove-haskell: 'true'
        # 如果空间还是不够用，可以把以下开启，清理出更多空间
        # remove-android: 'true'
        # remove-codeql: 'true'
        build-mount-path: '/var/lib/docker/'

    - name: Restart docker
      run: sudo service docker restart

    - name: Free up disk space complete
      run: |
        echo "Free up disk space complete"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Pull image
      run: |
        docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD ${{ vars.TARGET_REGISTRY }}
        while IFS= read -r line || [ -n "$line" ]; do
            # 忽略空行与注释
            [[ -z "$line" ]] && continue
            if echo "$line" | grep -q '^\s*#'; then
                continue
            fi
            
            echo "镜像名称: $line"
            docker pull "$line"
            docker tag "$line" "${{ vars.TARGET_REGISTRY }}/${{ vars.TARGET_NAMESPACE }}/$line"
            #docker push "${{ vars.TARGET_REGISTRY }}/${{ vars.TARGET_NAMESPACE }}/$line"

            # push 重试 3 次
            for i in {1..3}; do
              if docker push "${{ vars.TARGET_REGISTRY }}/${{ vars.TARGET_NAMESPACE }}/$line"; then
                echo "✅ Push 成功: $line"
                break
              else
                echo "⚠️ Push 失败 (第 $i 次)，等待 10 秒重试..."
                sleep 10
              fi
              if [ $i -eq 3 ]; then
                echo "❌ Push 多次失败: $line"
                exit 1
              fi
            done
            
        done < images.txt

