name: Docker Image Sync

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  TARGET_REGISTRY: "${{ secrets.TARGET_REGISTRY }}"
  TARGET_NAMESPACE: "${{ secrets.TARGET_NAMESPACE }}"
  ALIYUN_REGISTRY_USER: "${{ secrets.USERNAME }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.PASSWORD }}"
  env_var: ${{ vars.Docker }}
jobs:

  build:
    runs-on: ubuntu-latest
    environment: docker
    steps:
    - name: Before freeing up disk space
      run: |
        echo "Before freeing up disk space"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    # 增加可用磁盘空间
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:

        root-reserve-mb: 2048
        swap-size-mb: 128
        remove-dotnet: 'true'
        remove-haskell: 'true'
        # 如果空间还是不够用，可以把以下开启，清理出更多空间
        # remove-android: 'true'
        # remove-codeql: 'true'
        build-mount-path: '/var/lib/docker/'

    - name: Restart docker
      run: sudo service docker restart

    - name: Free up disk space complete
      run: |
        echo "Free up disk space complete"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Pull image
      run: |
        docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $TARGET_REGISTRY
        # declare -A duplicate_images
        # declare -A temp_map
        # docker pull "pinpointdocker/pinpoint-collector:3.0.1-metric"
        # docker tag "pinpointdocker/pinpoint-collector:3.0.1-metric" ${{ vars.TARGET_REGISTRY }}/${{ vars.TARGET_NAMESPACE }}/pinpointdocker/pinpoint-collector:3.0.1-metric
        # docker push ${{ vars.TARGET_REGISTRY }}/${{ vars.TARGET_NAMESPACE }}/pinpointdocker/pinpoint-collector:3.0.1-metric
        while IFS= read -r line || [ -n "$line" ]; do
            # 忽略空行与注释
            [[ -z "$line" ]] && continue
            if echo "$line" | grep -q '^\s*#'; then
                continue
            fi
            
            echo "镜像名称: $line"
            docker pull "$line"
            docker tag "$line" "${{ vars.TARGET_REGISTRY }}/${{ vars.TARGET_NAMESPACE }}/$line"
            docker push ${{ vars.TARGET_REGISTRY }}/${{ vars.TARGET_NAMESPACE }}/$line"
            
        done < images.txt

