name: Docker Image Sync

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  ALIYUN_REGISTRY: "${{ secrets.TARGET_REGISTRY }}"
  ALIYUN_NAME_SPACE: "${{ secrets.TARGET_NAMESPACE }}"
  ALIYUN_REGISTRY_USER: "${{ secrets.USERNAME }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.PASSWORD }}"
jobs:

  build:
    runs-on: ubuntu-latest
    environment: docker
    steps:
    - name: "输出变量"
      run: |
        echo ${{ env.ALIYUN_REGISTRY }}
    - name: Before freeing up disk space
      run: |
        echo "Before freeing up disk space"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    # 增加可用磁盘空间
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:

        root-reserve-mb: 2048
        swap-size-mb: 128
        remove-dotnet: 'true'
        remove-haskell: 'true'
        # 如果空间还是不够用，可以把以下开启，清理出更多空间
        # remove-android: 'true'
        # remove-codeql: 'true'
        build-mount-path: '/var/lib/docker/'

    - name: Restart docker
      run: sudo service docker restart

    - name: Free up disk space complete
      run: |
        echo "Free up disk space complete"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Pull image
      run: sh ./sync.sh

